### ISSUE TITLE
AttributeError: REQUEST when doing Plone upgrade.

### ISSUE THREAD

**Issue by mauritsvanrees** [4teamwork/ftw.upgrade#170] opened 2018-10-31 16:42 UTC
Steps to reproduce:
- Create a Plone 5.1.2 site. No add-ons, just `eggs = Plone`.
- Update the buildout to 5.1.4. Make sure ftw.upgrade is in the eggs.
- Start the site.
- Run `bin/upgrade plone_upgrade --all-sites`

Result:
- The command fails with exit code 1.
- The Plone upgrade has failed.
- The Plone log (`bin/instance fg`) shows this:

```
2018-10-31 17:30:06 INFO plone.app.upgrade Starting the migration from version: 5112
2018-10-31 17:30:06 INFO Products.GenericSetup.tool Importing profile profile-plone.app.upgrade.v51:to513 with dependency strategy ignore.
2018-10-31 17:30:06 INFO Products.GenericSetup.tool Applying main profile profile-plone.app.upgrade.v51:to513
2018-10-31 17:30:06 INFO GenericSetup.rolemap Role / permission map imported.
2018-10-31 17:30:06 INFO GenericSetup.plone.app.registry Removed record plone.resources/resource-plone-app-event-js.init.
2018-10-31 17:30:06 INFO GenericSetup.plone.app.registry Removed record plone.resources/resource-plone-app-event-js.export.
2018-10-31 17:30:06 INFO GenericSetup.plone.app.registry Removed record plone.resources/resource-plone-app-event-js.deps.
2018-10-31 17:30:06 INFO GenericSetup.plone.app.registry Removed record plone.resources/resource-plone-app-event-js.conf.
2018-10-31 17:30:06 INFO GenericSetup.plone.app.registry Removed record plone.resources/resource-plone-app-event-js.url.
2018-10-31 17:30:06 INFO GenericSetup.plone.app.registry Removed record plone.resources/resource-plone-app-event-js.css.
2018-10-31 17:30:06 INFO GenericSetup.plone.app.registry Removed record plone.resources/resource-plone-app-event-js.js.
2018-10-31 17:30:06 INFO GenericSetup.plone.app.registry Removed record plone.resources/resource-plone-app-event-css.init.
2018-10-31 17:30:06 INFO GenericSetup.plone.app.registry Removed record plone.resources/resource-plone-app-event-css.export.
2018-10-31 17:30:06 INFO GenericSetup.plone.app.registry Removed record plone.resources/resource-plone-app-event-css.deps.
2018-10-31 17:30:06 INFO GenericSetup.plone.app.registry Removed record plone.resources/resource-plone-app-event-css.conf.
2018-10-31 17:30:06 INFO GenericSetup.plone.app.registry Removed record plone.resources/resource-plone-app-event-css.url.
2018-10-31 17:30:06 INFO GenericSetup.plone.app.registry Removed record plone.resources/resource-plone-app-event-css.css.
2018-10-31 17:30:06 INFO GenericSetup.plone.app.registry Removed record plone.resources/resource-plone-app-event-css.js.
2018-10-31 17:30:06 ERROR plone.app.upgrade Upgrade aborted. Error:
Traceback (most recent call last):
  File "/Users/maurits/shared-eggs/cp27m/Products.CMFPlone-5.1.4-py2.7.egg/Products/CMFPlone/MigrationTool.py", line 294, in upgrade
    step['step'].doStep(setup)
  File "/Users/maurits/shared-eggs/cp27m/Products.GenericSetup-1.8.10-py2.7.egg/Products/GenericSetup/upgrade.py", line 201, in doStep
    ignore_dependencies=ign_deps)
  File "/Users/maurits/shared-eggs/cp27m/Products.GenericSetup-1.8.10-py2.7.egg/Products/GenericSetup/tool.py", line 388, in runAllImportStepsFromProfile
    dependency_strategy=dependency_strategy)
  File "/Users/maurits/shared-eggs/cp27m/Products.GenericSetup-1.8.10-py2.7.egg/Products/GenericSetup/tool.py", line 1469, in _runImportStepsFromContext
    message = self._doRunImportStep(step, context)
  File "/Users/maurits/shared-eggs/cp27m/Products.GenericSetup-1.8.10-py2.7.egg/Products/GenericSetup/tool.py", line 1281, in _doRunImportStep
    return handler(context)
  File "/Users/maurits/shared-eggs/cp27m/Products.CMFPlone-5.1.4-py2.7.egg/Products/CMFPlone/resources/exportimport/bundles.py", line 39, in combine
    combine_bundles(site)
  File "/Users/maurits/shared-eggs/cp27m/Products.CMFPlone-5.1.4-py2.7.egg/Products/CMFPlone/resources/browser/combine.py", line 169, in combine_bundles
    write_js(context, production_folder, 'default')
  File "/Users/maurits/shared-eggs/cp27m/Products.CMFPlone-5.1.4-py2.7.egg/Products/CMFPlone/resources/browser/combine.py", line 83, in write_js
    registry.records['plone.resources/jquery.js'].value
  File "/Users/maurits/shared-eggs/cp27m/Products.CMFPlone-5.1.4-py2.7.egg/Products/CMFPlone/resources/browser/combine.py", line 48, in get_resource
    resource = context.unrestrictedTraverse(path)
  File "/Users/maurits/shared-eggs/cp27m/Zope2-2.13.27-py2.7.egg/OFS/Traversable.py", line 274, in unrestrictedTraverse
    next = queryMultiAdapter((obj, aq_acquire(self, 'REQUEST')),
AttributeError: REQUEST
2018-10-31 17:30:06 ERROR Zope.SiteErrorLog 1541003406.690.32707543274 http://localhost:8080/Plone/upgrades-api/plone_upgrade
Traceback (innermost last):
  Module ZPublisher.Publish, line 138, in publish
  Module ZPublisher.mapply, line 77, in mapply
  Module ZPublisher.Publish, line 48, in call_object
  Module ftw.upgrade.jsonapi.utils, line 121, in json_wrapper
  Module ftw.upgrade.jsonapi.utils, line 102, in action_wrapper
  Module ftw.upgrade.jsonapi.plonesite, line 107, in plone_upgrade
  Module <string>, line 3, in upgrade
  Module AccessControl.requestmethod, line 70, in _curried
  Module Products.CMFPlone.MigrationTool, line 294, in upgrade
  Module Products.GenericSetup.upgrade, line 201, in doStep
  Module Products.GenericSetup.tool, line 388, in runAllImportStepsFromProfile
   - __traceback_info__: profile-plone.app.upgrade.v51:to513
  Module Products.GenericSetup.tool, line 1469, in _runImportStepsFromContext
  Module Products.GenericSetup.tool, line 1281, in _doRunImportStep
   - __traceback_info__: combine-bundles
  Module Products.CMFPlone.resources.exportimport.bundles, line 39, in combine
  Module Products.CMFPlone.resources.browser.combine, line 169, in combine_bundles
  Module Products.CMFPlone.resources.browser.combine, line 83, in write_js
  Module Products.CMFPlone.resources.browser.combine, line 48, in get_resource
  Module OFS.Traversable, line 274, in unrestrictedTraverse
   - __traceback_info__: (['jquery.min.js', 'dist', 'jquery', 'components'], '++plone++static')
AttributeError: REQUEST
```

So the `combine-bundles` import step needs the `REQUEST` on the context.
When I add a pdb in `browser/combine.py` line 48 (near the end of the traceback), I see that `context` is the Plone Site, and it has no `REQUEST` attribute. A request could possibly be found:

```
(Pdb) from zope.globalrequest import getRequest
(Pdb) getRequest()
<HTTPRequest, URL=http://localhost:8080/Plone/upgrades-api/plone_upgrade>
```

When I try it in the browser with the standard `@@plone-upgrade` form, it works fine: the upgrade works.

I wonder if this could be fixed in `ftw.upgrade`.

**Comment by lukasgraf** [comment] 2018-10-31 19:57
@mauritsvanrees thanks for your clear and detailed bug report!

I was able to reproduce the issue exactly as you described it.

I believe we're hitting the issue that is alluded to in [this comment in `QuickInstallerTool.py`](https://github.com/plone/Products.CMFQuickInstallerTool/blob/81696c5e060f26fe25371825e27df1bbf287caa5/Products/CMFQuickInstallerTool/QuickInstallerTool.py#L584-L587): Apparently, fetching the `portal_setup` tool using `getToolByName` (instead of acquisition) results in it missing a `RequestContainer`.

And that is indeed what we're doing in `ftw.upgrade` - for both the [`portal_setup`](https://github.com/4teamwork/ftw.upgrade/blob/7b259909dcef25a14c0e1bf55018be0a0d0759d0/ftw/upgrade/jsonapi/plonesite.py#L21) and [`portal_migration`](https://github.com/4teamwork/ftw.upgrade/blob/7b259909dcef25a14c0e1bf55018be0a0d0759d0/ftw/upgrade/jsonapi/plonesite.py#L99-L116) tools used during Plone upgrades, as well as in other places.

Whereas the standard `@@plone-upgrade` view [uses `getattr` instead](https://github.com/plone/Products.CMFPlone/blob/d43517ed9ca0593cf74c0d013fe7a933c912fe5e/Products/CMFPlone/browser/admin.py#L284).

So if you're pressed for time until we can release a fix, switching to `getattr` instead of `getToolByName` in these places seems to do the trick as a workaround.

---

It seems that is also why [`test_upgrade_plone` needed to be skipped](https://github.com/4teamwork/ftw.upgrade/blob/7b259909dcef25a14c0e1bf55018be0a0d0759d0/ftw/upgrade/tests/test_command_plone_upgrade.py#L24) for Plone 5 - currently this test runs into exactly this issue (just in other contexts), and gets a lot further once we use `getattr` instead of `getToolByName`.

(*Note to self: Next, that test stumbles on an issue where [ATContenttypes and plone.app.contenttypes profiles step on each other's feet](https://github.com/plone/Products.CMFPlone/issues/382) during Plone 4 -> 5 upgrade, and after that it hits an issue in a Plone 5 upgrade step that got [fixed in a more recent version](https://github.com/plone/plone.app.upgrade/commit/e0a48eb3131799b13c271adcd4990649a1ca502b#diff-0550ccfaf80dd4d986594aff82f94fc0R270)*)

**Comment by fredvd** [comment] 2019-03-26 21:47
@lukasgraf Is this issue still something on the radar?  I got bitten by it while performing an upgrade to Plone 5.1.5  this evening :-P

Is the proposed workaround to user getattr / aq_get in the plone_upgrade code in ftw.upgrade something that could be done permanent, or do you want to create/get hold of a RequestContainer?

**Comment by lukasgraf** [comment] 2019-04-02 07:13
@fredvd it's definitely still on the radar, and I consider it a bug that needs fixing. Just haven't gotten around to it, sorry.

I've briefly looked into this with @jone, and we're still a bit hesitant to just rewrite the code to use `getattr` to acquire the `portal_...` tools, since that's usually an explicit anti-pattern in Plone. So we don't want to blindly rewrite that just yet, before we really understand what's going on. On the other hand, manually getting a hold of a RequestContainer and inserting it into the AQ chain also feels off, that shouldn't be necessary.

So we're also not actively looking for PRs on this one, if I may be so blunt ;) It's more that we need a bit more time to investigate to determine what the sensible approach is here.

**Comment by fredvd** [comment] 2019-04-02 09:17
@mauritsvanrees Since you are 'mr. portal_setup' since a a few rewrites around the installer, do you have some thoughts on what might be the "least unsensible" approach here? ;-)

**Comment by mauritsvanrees** [comment] 2019-04-29 13:37
I had another look at this, and I think it is quite safe to use `getattr` to get the migration tool, especially because you already saw that core Plone does this too. Let me explain. And let me figure this out while I write. :-)

To recap what [`getToolByName`](https://github.com/zopefoundation/Products.CMFCore/blob/2.3.0/Products/CMFCore/utils.py#L89) does:

- Check if a utility is registered for the given name.
- Try to get this utility and if this works, do a few extra checks, like: is it acquisition wrapped.
- If it fails, fall back to using `getattr` to get an object with this name using acquisition.

I think more tools were at some point registered as utility.  For some this was removed, because they can _never_ work as a utility.  For example, `portal_catalog` needs to be an actual object in the site, because all kinds of indexes and metadata are stored there.

The `portal_migration` tool would _seem_ to be a good candidate for use as a utility, because there is nothing stored there. But when using it as utility, you apparently lose the request. And when the `portal_migration` tool then gets its `portal_setup` tool, then this does not have a `REQUEST` either:

```
(Pdb) self.context
<PloneSite at /Plone>
(Pdb) self.context.REQUEST
<HTTPRequest, URL=http://localhost:8080/Plone/upgrades-api/plone_upgrade>
(Pdb) getToolByName(self.context, 'portal_setup').REQUEST
<HTTPRequest, URL=http://localhost:8080/Plone/upgrades-api/plone_upgrade>
(Pdb) getToolByName(self.context, 'portal_migration').REQUEST
*** AttributeError: REQUEST
(Pdb) getToolByName(getToolByName(self.context, 'portal_migration'), 'portal_setup')
<SetupTool at /Plone/portal_setup used for /Plone/portal_migration>
(Pdb) getToolByName(getToolByName(self.context, 'portal_migration'), 'portal_setup').REQUEST
*** AttributeError: REQUEST
```

So it seems better if `CMFPlone` would not register `portal_migration` as [tool utility](https://github.com/plone/Products.CMFPlone/blob/d43517ed9ca0593cf74c0d013fe7a933c912fe5e/Products/CMFPlone/MigrationTool.py#L371).  As a consequence, it should be fine for `ftw.upgrade` to use `getattr`.

In fact, when I edit `Products.CMFPlone/browser/admin.py` to use `getToolByName` to get `portal_migration`, and I try a migration in the Plone UI, so _without_ `ftw.upgrade`, it fails in the same way:

```
2019-04-29 15:15:25 INFO plone.app.upgrade Starting the migration from version: 5114
2019-04-29 15:15:25 INFO Products.GenericSetup.tool Importing profile profile-plone.app.upgrade.v51:to515 with dependency strategy ignore.
2019-04-29 15:15:25 INFO Products.GenericSetup.tool Applying main profile profile-plone.app.upgrade.v51:to515
2019-04-29 15:15:25 INFO GenericSetup.rolemap Role / permission map imported.
2019-04-29 15:15:25 ERROR plone.app.upgrade Upgrade aborted. Error:
Traceback (most recent call last):
  File "/Users/maurits/shared-eggs/cp27m/Products.CMFPlone-5.1.5-py2.7.egg/Products/CMFPlone/MigrationTool.py", line 294, in upgrade
    step['step'].doStep(setup)
  File "/Users/maurits/shared-eggs/cp27m/Products.GenericSetup-1.8.10-py2.7.egg/Products/GenericSetup/upgrade.py", line 201, in doStep
    ignore_dependencies=ign_deps)
  File "/Users/maurits/shared-eggs/cp27m/Products.GenericSetup-1.8.10-py2.7.egg/Products/GenericSetup/tool.py", line 388, in runAllImportStepsFromProfile
    dependency_strategy=dependency_strategy)
  File "/Users/maurits/shared-eggs/cp27m/Products.GenericSetup-1.8.10-py2.7.egg/Products/GenericSetup/tool.py", line 1469, in _runImportStepsFromContext
    message = self._doRunImportStep(step, context)
  File "/Users/maurits/shared-eggs/cp27m/Products.GenericSetup-1.8.10-py2.7.egg/Products/GenericSetup/tool.py", line 1281, in _doRunImportStep
    return handler(context)
  File "/Users/maurits/shared-eggs/cp27m/Products.CMFPlone-5.1.5-py2.7.egg/Products/CMFPlone/resources/exportimport/bundles.py", line 39, in combine
    combine_bundles(site)
  File "/Users/maurits/shared-eggs/cp27m/Products.CMFPlone-5.1.5-py2.7.egg/Products/CMFPlone/resources/browser/combine.py", line 192, in combine_bundles
    default_writer.write_js()
  File "/Users/maurits/shared-eggs/cp27m/Products.CMFPlone-5.1.5-py2.7.egg/Products/CMFPlone/resources/browser/combine.py", line 92, in write_js
    self.registry.records['plone.resources/jquery.js'].value)
  File "/Users/maurits/shared-eggs/cp27m/Products.CMFPlone-5.1.5-py2.7.egg/Products/CMFPlone/resources/browser/combine.py", line 49, in get_resource
    resource = context.unrestrictedTraverse(path)
  File "/Users/maurits/shared-eggs/cp27m/Zope2-2.13.27-py2.7.egg/OFS/Traversable.py", line 274, in unrestrictedTraverse
    next = queryMultiAdapter((obj, aq_acquire(self, 'REQUEST')),
AttributeError: REQUEST
2019-04-29 15:15:25 INFO plone.app.upgrade End of upgrade path, main migration has finished.
2019-04-29 15:15:25 ERROR plone.app.upgrade The upgrade path did NOT reach current version.
2019-04-29 15:15:25 ERROR plone.app.upgrade Migration has failed
```

This depends on which upgrade step is run, because not every upgrade step will need the request. But apparently doing a traverse is already enough to trigger this.

**Comment by lukasgraf** [comment] 2019-04-29 14:38
@mauritsvanrees thank you very much for that excellent explanation and investigation!

So, when you say

> So it seems better if CMFPlone would not register portal_migration as tool utility.

this could be loosely rephrased to

"registering a tool as a utility sort of implies that it can be pulled out of thin air, and shouldn't require an acquisition context to perform its operation. Which is not strictly the case for the `portal_migration` tool, which is why it would better not be registered as a utility, because then `getToolByName` would look it up via acquisition"

right?

So this pretty much settles it for me, I think `ftw.upgrade` should use `getToolByName` here as well. It's subtle, and one could argue that it's sort of a bug in `Products.CMFPlone`, but it's what we need to do for things to work [tm].

We're currently at the end of a release cycle so I'm pretty swamped this week (and so is @jone I think), but I'd be happy to review & merge PRs for this.

Thanks again for your thorough analysis! 💚

**Comment by mauritsvanrees** [comment] 2019-04-29 14:47
> right?

Right.

> So this pretty much settles it for me, I think ftw.upgrade should use getToolByName here as well.

No, ftw.upgrade is _currently_ using getToolByName, and _should_ switch to getattr. I might have gotten you confused. :-)

**Comment by lukasgraf** [comment] 2019-04-29 14:50
Eh, that's what I meant ;-) I'm working on very little sleep today, definitely not a fault of your's for confusing me ;-)

**Comment by mauritsvanrees** [comment] 2019-04-29 14:51
I thought that might be the case yes. :-)
Good luck this week!

**Closed** 2019-06-19 09:45 UTC
